title: Web Testing
description: Testing with Jeykll & the Just the Docs theme
theme: just-the-docs

url: https://40tude.github.io/web_testing/

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
